trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'danilenzo/devops'
    command: 'buildAndPush'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Danil Vorobjov DevOps(f53e97b6b6120be2b4e74be03cc64a336ad29a76)'
    azureResourceGroup: 'networking-rg'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'